/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.akka.io/maven")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.apache.logging.log4j:log4j-core:2.20.0")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3")
    api("ch.qos.logback:logback-classic:1.2.3")
    api("org.json:json:20230618")
    api("com.typesafe.akka:akka-cluster-typed_2.13:2.8.5")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testImplementation("org.junit.platform:junit-platform-runner:1.10.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.9.0")
}

group = "org.dawn.lgfs"
version = "1.0-SNAPSHOT"
description = "LGFS"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
