services:
  master:
    image: lgfs:latest
    environment:
      NODE_PORT: 2551
      API_PORT: 3000
      DATA_PORT: 9005
      HOST_NAME: "master"
      NODE_ROLE: "master"
      CONF_PATH: "/app/conf/application.conf"
      NODE_TYPE: "server"
    ports:
      - "2551:2551"
      - "9005:9005"
      - "3000:3000"
    volumes:
      - type: bind
        source: "./app/src/main/resources/application.conf"
        target: "/app/conf/application.conf"
      - type: bind
        source: "./app/src/main/resources/test.txt"
        target: "/app/conf/test.txt"
      - gfs:/gfs/
    profiles: [ "master","all" ]

  chunk-1:
    image: lgfs:latest
    ports:
      - "2552:2552"
      - "5000:5000"
      - "9006:9006"

    environment:
      NODE_PORT: 2552
      API_PORT: 5000
      DATA_PORT: 9006
      HOST_NAME: "chunk-1"
      CONF_PATH: "/app/conf/application.conf"
      NODE_TYPE: "server"
    volumes:
      - type: bind
        source: "./app/src/main/resources/chunk.conf"
        target: "/app/conf/application.conf"
      - gfs:/gfs/
    profiles: [ "chunk","all" ]

  chunk-2:
    image: lgfs:latest
    ports:
      - "2553:2553"
      - "4001:4001"
      - "9007:9007"
    environment:
      NODE_PORT: 2553
      API_PORT: 4001
      DATA_PORT: 9007
      HOST_NAME: "chunk-2"
      CONF_PATH: "/app/conf/application.conf"
      NODE_TYPE: "server"
    volumes:
      - type: bind
        source: "./app/src/main/resources/chunk.conf"
        target: "/app/conf/application.conf"
      - gfs:/gfs/
    profiles: [ "chunk","all" ]

  chunk-3:
    image: lgfs:latest
    ports:
      - "2554:2554"
      - "4003:4003"
      - "9011:9011"
    environment:
      NODE_PORT: 2554
      API_PORT: 4003
      DATA_PORT: 9011
      HOST_NAME: "chunk-3"
      CONF_PATH: "/app/conf/application.conf"
      NODE_TYPE: "server"
    volumes:
      - type: bind
        source: "./app/src/main/resources/chunk.conf"
        target: "/app/conf/application.conf"
    profiles: [ "chunk","all" ]

  chunk-4:
    image: lgfs:latest
    ports:
      - "2555:2555"
      - "4004:4004"
      - "9012:9012"

    environment:
      NODE_PORT: 2555
      API_PORT: 4004
      DATA_PORT: 90012
      HOST_NAME: "chunk-4"
      CONF_PATH: "/app/conf/application.conf"
      NODE_TYPE: "server"
    volumes:
      - type: bind
        source: "./app/src/main/resources/chunk.conf"
        target: "/app/conf/application.conf"
    profiles: [ "chunk","all" ]


volumes:
  gfs:

#networks:
#  static-network:
#    ipam:
 #     config:
#        - subnet: 172.20.0.0/16